@startuml
title Employee Login Sequence

actor User
participant frontend
participant GetCredentialsLambda
database Employee_Credentials

User -> frontend: Enter login credentials
frontend -> frontend: Validate credentials format
alt Incorrect format
    frontend -> User: Display error
else Correct format
    frontend -> GetCredentialsLambda: Send credentials
    GetCredentialsLambda -> Employee_Credentials: Retrieve credentials
    alt Credentials don't exist
        Employee_Credentials -> GetCredentialsLambda: Return error
        GetCredentialsLambda -> frontend: Throw error
        frontend -> User: Display error
    else Account locked
        Employee_Credentials -> GetCredentialsLambda: Return account locked
        GetCredentialsLambda -> frontend: Throw error
        frontend -> User: Display error
    else Credentials valid
        Employee_Credentials -> GetCredentialsLambda: Return credentials
        GetCredentialsLambda -> frontend: Return credentials
        frontend -> User: Login successful
    end
end



newpage Updating Employee Credentials Sequence

actor User
participant frontend
participant UpdateCredentialsLambda
database Employee_Credentials

User -> frontend: Enter new credentials
frontend -> frontend: Validate credentials format
alt Incorrect format
    frontend -> User: Display error
else Correct format
    frontend -> UpdateCredentialsLambda: Send new credentials
    UpdateCredentialsLambda -> Employee_Credentials: Update credentials
    alt Update successful
        Employee_Credentials -> UpdateCredentialsLambda: Return success
        UpdateCredentialsLambda -> frontend: Return success
        frontend -> User: Display success message
    else Update failed
        Employee_Credentials -> UpdateCredentialsLambda: Return error
        UpdateCredentialsLambda -> frontend: Throw error
        frontend -> User: Display error
    end
end



newpage Creating Employee Credentials Sequence

actor User
note left of User: Admin User

participant frontend
participant CreateCredentialsLambda
database Employee_Credentials

User -> frontend: Enter new credentials
frontend -> frontend: Validate credentials format
alt Incorrect format
    frontend -> User: Display error
else Correct format
    frontend -> CreateCredentialsLambda: Send new credentials
    CreateCredentialsLambda -> Employee_Credentials: Create credentials
    alt Creation successful
        Employee_Credentials -> CreateCredentialsLambda: Return success
        CreateCredentialsLambda -> frontend: Return success
        frontend -> User: Display success message
    else Creation failed
        Employee_Credentials -> CreateCredentialsLambda: Return error
        CreateCredentialsLambda -> frontend: Throw error
        frontend -> User: Display error
    end
end
@enduml
